name: xi
version: 0.0.1

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.3+1
  xml2json: ^6.2.3
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.1.1
  awesome_dio_interceptor: ^1.2.0
  dio_cache_interceptor: ^3.5.0
  path_provider: ^2.1.3
  jsonc: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter